version: '2.3'
networks:
  lb_web:
    external: true
  back:
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet: 10.0.${SUBNET}.0/24
services:
  redis:
    image: redis:alpine
    volumes:
    - ./data:/data
    command: redis-server --appendonly yes
    networks:
    - back
  web:
    image: nginx
    depends_on:
    - app
    volumes:
    - ./nginx.conf:/etc/nginx/nginx.conf:ro
    environment:
    - VIRTUAL_HOST
    networks:
    - back
    - lb_web
  app:
    image: audreyt/ethercalc
    depends_on:
    - redis
    networks:
    - back
